import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { AddQueue } from './components/addQueue'
import { Card } from './components/card'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Imaginary Queue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Welcome to a Restaurant!
        </h2>

        <p className={styles.description}>
          Input your name to get your queue number
        </p>

        <AddQueue />

        <div className={styles.grid}>
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
