import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { AddQueue } from './components/AddQueue'
import { ListCard } from './components/Card'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Imaginary Queue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.telkom}>
          <Image src="/telkom.svg" alt="Telkom Logo" width={150} height={100} />
        </span>

        <h2 className={styles.title}>
          Welcome to <span className={styles.anon}>Anon Customer Service!</span>
        </h2>

        <p className={styles.description}>
          Please enter your name to get your queue number. The staff will call you according to the number.
        </p>

        <AddQueue />

        <div className={styles.grid}>
          <ListCard />
        </div>
      </main>

      <footer className={styles.footer}>
        2022 @ Alsabila Shakina Prasetyo
      </footer>
    </div>
  )
}
